
class CPU():
    properties = {
        'label': 'CPU',
        'name': 'null',
        'price': 'null',
        'brand': 'null',
        'serie': 'null',
        'product': 'null',  # eerste gedeelte van de productnaam
        'socket': 'null',
        'amountOfCores': 'null',
        'speed': 'null',
        'thermalDesignPower': 'null',
        'CPUsSpecNumber': 'null',
        'maxiTurboFrequency': 'null',
        'memorySpecification': 'null',
        'busSpeed': 'null',
        'procesTechnology': 'null',
        'intergratedGraphics': 'null',
        'gpu': 'null',
        'nominalSpeedVideochip': 'null',
        'maxSpeedVideochip': 'null',
        'CPUCacheLevel1': 'null',
        'CPUCacheLevel2': 'null',
        'CPUCacheLevel3': 'null',
        'threads': 'null',
        'virtualisation': 'null',
        'CPUMultiplier': 'null',
        'CPUStepping': 'null',
        'CPUInstructionSet': 'null',
        'typeCooling': 'null',
        'guarantee': 'null',
        'EAN': 'null',
        'SKU': 'null'
    }
